// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbgen

import (
	"context"
	"database/sql"

	"github.com/WNTR-Software/foxcal/backend/storage/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSampleKv(db *gorm.DB, opts ...gen.DOOption) sampleKv {
	_sampleKv := sampleKv{}

	_sampleKv.sampleKvDo.UseDB(db, opts...)
	_sampleKv.sampleKvDo.UseModel(&models.SampleKv{})

	tableName := _sampleKv.sampleKvDo.TableName()
	_sampleKv.ALL = field.NewAsterisk(tableName)
	_sampleKv.ID = field.NewUint(tableName, "id")
	_sampleKv.CreatedAt = field.NewTime(tableName, "created_at")
	_sampleKv.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sampleKv.DeletedAt = field.NewField(tableName, "deleted_at")
	_sampleKv.Key = field.NewString(tableName, "key")
	_sampleKv.Value = field.NewString(tableName, "value")

	_sampleKv.fillFieldMap()

	return _sampleKv
}

type sampleKv struct {
	sampleKvDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Key       field.String
	Value     field.String

	fieldMap map[string]field.Expr
}

func (s sampleKv) Table(newTableName string) *sampleKv {
	s.sampleKvDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sampleKv) As(alias string) *sampleKv {
	s.sampleKvDo.DO = *(s.sampleKvDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sampleKv) updateTableName(table string) *sampleKv {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.Key = field.NewString(table, "key")
	s.Value = field.NewString(table, "value")

	s.fillFieldMap()

	return s
}

func (s *sampleKv) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sampleKv) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["key"] = s.Key
	s.fieldMap["value"] = s.Value
}

func (s sampleKv) clone(db *gorm.DB) sampleKv {
	s.sampleKvDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sampleKv) replaceDB(db *gorm.DB) sampleKv {
	s.sampleKvDo.ReplaceDB(db)
	return s
}

type sampleKvDo struct{ gen.DO }

type ISampleKvDo interface {
	gen.SubQuery
	Debug() ISampleKvDo
	WithContext(ctx context.Context) ISampleKvDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISampleKvDo
	WriteDB() ISampleKvDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISampleKvDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISampleKvDo
	Not(conds ...gen.Condition) ISampleKvDo
	Or(conds ...gen.Condition) ISampleKvDo
	Select(conds ...field.Expr) ISampleKvDo
	Where(conds ...gen.Condition) ISampleKvDo
	Order(conds ...field.Expr) ISampleKvDo
	Distinct(cols ...field.Expr) ISampleKvDo
	Omit(cols ...field.Expr) ISampleKvDo
	Join(table schema.Tabler, on ...field.Expr) ISampleKvDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISampleKvDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISampleKvDo
	Group(cols ...field.Expr) ISampleKvDo
	Having(conds ...gen.Condition) ISampleKvDo
	Limit(limit int) ISampleKvDo
	Offset(offset int) ISampleKvDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISampleKvDo
	Unscoped() ISampleKvDo
	Create(values ...*models.SampleKv) error
	CreateInBatches(values []*models.SampleKv, batchSize int) error
	Save(values ...*models.SampleKv) error
	First() (*models.SampleKv, error)
	Take() (*models.SampleKv, error)
	Last() (*models.SampleKv, error)
	Find() ([]*models.SampleKv, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SampleKv, err error)
	FindInBatches(result *[]*models.SampleKv, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SampleKv) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISampleKvDo
	Assign(attrs ...field.AssignExpr) ISampleKvDo
	Joins(fields ...field.RelationField) ISampleKvDo
	Preload(fields ...field.RelationField) ISampleKvDo
	FirstOrInit() (*models.SampleKv, error)
	FirstOrCreate() (*models.SampleKv, error)
	FindByPage(offset int, limit int) (result []*models.SampleKv, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISampleKvDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sampleKvDo) Debug() ISampleKvDo {
	return s.withDO(s.DO.Debug())
}

func (s sampleKvDo) WithContext(ctx context.Context) ISampleKvDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sampleKvDo) ReadDB() ISampleKvDo {
	return s.Clauses(dbresolver.Read)
}

func (s sampleKvDo) WriteDB() ISampleKvDo {
	return s.Clauses(dbresolver.Write)
}

func (s sampleKvDo) Session(config *gorm.Session) ISampleKvDo {
	return s.withDO(s.DO.Session(config))
}

func (s sampleKvDo) Clauses(conds ...clause.Expression) ISampleKvDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sampleKvDo) Returning(value interface{}, columns ...string) ISampleKvDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sampleKvDo) Not(conds ...gen.Condition) ISampleKvDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sampleKvDo) Or(conds ...gen.Condition) ISampleKvDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sampleKvDo) Select(conds ...field.Expr) ISampleKvDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sampleKvDo) Where(conds ...gen.Condition) ISampleKvDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sampleKvDo) Order(conds ...field.Expr) ISampleKvDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sampleKvDo) Distinct(cols ...field.Expr) ISampleKvDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sampleKvDo) Omit(cols ...field.Expr) ISampleKvDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sampleKvDo) Join(table schema.Tabler, on ...field.Expr) ISampleKvDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sampleKvDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISampleKvDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sampleKvDo) RightJoin(table schema.Tabler, on ...field.Expr) ISampleKvDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sampleKvDo) Group(cols ...field.Expr) ISampleKvDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sampleKvDo) Having(conds ...gen.Condition) ISampleKvDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sampleKvDo) Limit(limit int) ISampleKvDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sampleKvDo) Offset(offset int) ISampleKvDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sampleKvDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISampleKvDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sampleKvDo) Unscoped() ISampleKvDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sampleKvDo) Create(values ...*models.SampleKv) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sampleKvDo) CreateInBatches(values []*models.SampleKv, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sampleKvDo) Save(values ...*models.SampleKv) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sampleKvDo) First() (*models.SampleKv, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SampleKv), nil
	}
}

func (s sampleKvDo) Take() (*models.SampleKv, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SampleKv), nil
	}
}

func (s sampleKvDo) Last() (*models.SampleKv, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SampleKv), nil
	}
}

func (s sampleKvDo) Find() ([]*models.SampleKv, error) {
	result, err := s.DO.Find()
	return result.([]*models.SampleKv), err
}

func (s sampleKvDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SampleKv, err error) {
	buf := make([]*models.SampleKv, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sampleKvDo) FindInBatches(result *[]*models.SampleKv, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sampleKvDo) Attrs(attrs ...field.AssignExpr) ISampleKvDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sampleKvDo) Assign(attrs ...field.AssignExpr) ISampleKvDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sampleKvDo) Joins(fields ...field.RelationField) ISampleKvDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sampleKvDo) Preload(fields ...field.RelationField) ISampleKvDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sampleKvDo) FirstOrInit() (*models.SampleKv, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SampleKv), nil
	}
}

func (s sampleKvDo) FirstOrCreate() (*models.SampleKv, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SampleKv), nil
	}
}

func (s sampleKvDo) FindByPage(offset int, limit int) (result []*models.SampleKv, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sampleKvDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sampleKvDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sampleKvDo) Delete(models ...*models.SampleKv) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sampleKvDo) withDO(do gen.Dao) *sampleKvDo {
	s.DO = *do.(*gen.DO)
	return s
}
